runtime: java17  # Use java11 or another compatible Java runtime
instance_class: F2  # Optional: specify the instance class
service: newbkend

handlers:
  - url: /.*
    script: this field is required, but ignored
